#ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tech
  namespace: coding
spec:
  rules:
    - host: tech.coding-space.cn
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tech
                port:
                  number: 80
---
#service
apiVersion: v1
kind: Service
metadata:
  name: tech
  namespace: coding
  annotations:
    "nginx.ingress.kubernetes.io/proxy-body-size": "300m"
spec:
  selector:
    app: tech
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech
  namespace: coding
spec:
  minReadySeconds: 10
  selector:
    matchLabels:
      app: tech
  replicas: 1
  template:
    metadata:
      labels:
        app: tech
    spec:
      containers:
        - name: tech
          image: registry.cn-beijing.aliyuncs.com/guanweiming/tech:${project_version}
