version: '3'
services:
  nacos:
    build:
      context: ./
    image: docker.pkg.github.com/guangee/dev/nacos:1.4.0
    restart: always
    container_name: nacos
    ports:
      - 8848:8848
    environment:
      - mysql_url=mysql
      - db_port=3306
      - db_name=nacos
      - db_username=nacos
      - db_password=nacos
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.21
    container_name: nacos_mysql
    restart: always
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nacos
      MYSQL_USER: nacos
      MYSQL_PASSWORD: nacos
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data/:/var/lib/mysql
      - ./mysql/conf/:/etc/mysql/conf.d/
      # 初始化目录
      - ./mysql/init/:/docker-entrypoint-initdb.d/
    command:
      # 将mysql8.0默认密码策略 修改为 原先 策略 (mysql8.0对其默认策略做了更改 会导致密码无法匹配)
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
