name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: 登陆docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login docker.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push image
        run: |
          echo "构建"
         docker build -t guangee/nacos:1.4.2 nacos/1.4.2/
         docker push guangee/nacos:1.4.2
#          docker build -t guangee/gitbook:3.2.3 gitbook/3.2.3/
#          docker push guangee/gitbook:3.2.3
#          docker build -t guangee/nacos:1.4.0 nacos/1.4.0/
#          docker push guangee/nacos:1.4.0

